### ISSUE TITLE
Instructions to compile

### ISSUE THREAD

**Issue by AlbertShown** [petabyt/webui-demo#1]
It would be better if there were compile instructions, something like this:

```
gcc fs.c -c -o fs.o
gcc main.c -c -o main.o
gcc -o app main.o fs.o -L. -lwebui-2-static-x64
```

Or even better with a `makefile`

**Comment by petabyt** [comment]
There is a makefile, I guess you didn't see it 🙂

**Comment by AlbertShown** [comment]
Sorry! I didn't see it. My bad 🤦‍♂️

The `makefile` expect that WebUI is in `~/Pulled/webui`, which is not the case. I suggest [fixing it here](https://github.com/petabyt/webui-demo/issues/2).
