### ISSUE TITLE
WebUI not available

### ISSUE THREAD

**Issue by AlbertShown** [petabyt/webui-demo#2]
The WebUI repo right now does not have an installation package. So, this repo should add WebUI repo as a submodule or simply manually add `webui.h` and `libwebui-2-static-x64.a` to this repo.

**Comment by petabyt** [comment]
Adding object files into a repository is generally considered bad practice. From what I read, you are planning on fixing your build system to not do that.

**Comment by AlbertShown** [comment]
Yes, so probably adding it as a submodule is the best thing to do 👍

**Comment by petabyt** [comment]
That would be ideal, but the webui repository is very large from all the object files (I think it was around 20mb) do you plan on purging these files from the git history anytime soon?

**Comment by AlbertShown** [comment]
We are planning to remove object files only. Purging the history will remove the full history commits, which is not good.

**Comment by petabyt** [comment]
No, not purging the history, but purging the file data from from the history. Git BFG can do it.

**Comment by AlbertShown** [comment]
@hassandraga

**Comment by petabyt** [comment]
@AlbertShown you can use this as an example for webui if you like. fs.c probably only works with GCC though.
